version: "3"

services:
  # admin:
  #   image: admin
  #   build:
  #     context: ./admin
  #     dockerfile: Dockerfile
  #   ports:
  #     - "6710:8989"
  web:
    image: web
    container_name: my_web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载项目
    restart: on-failure
    ports:
      - 80:80
